"""Run the lab's two hot paths against the PRODUCTION stack and report the delta.

The lite path keeps everything in-process: Qdrant in memory, Feast on SQLite +
Parquet. That is the right default for a laptop, but it hides the two things
that actually decide whether this design survives contact with production:

  * the vector index is a **network service** with persistence and payload
    indexes, not a dict that dies with the notebook kernel;
  * the online feature store is **Redis**, shared by every replica, instead of
    a SQLite file that only the local process can read.

So this script re-runs the same measurements as NB3 and NB4 against
Qdrant server + Redis + Postgres, and prints them next to the lite numbers.

    docker compose up -d
    python scripts/docker_path_report.py

Why the committed `app/feast_repo/feature_store.yaml` is NOT switched over:
`make notebooks` on a grader's machine must work with no Docker at all. This
script therefore GENERATES a second Feast repo (`app/feast_repo_docker/`,
gitignored) instead of editing the one the lite path depends on. Ports come
from the environment so a host that already owns 6379 can move it without the
repo carrying a machine-specific value.
"""
from __future__ import annotations

import json
import os
import statistics as stats
import subprocess
import sys
import time
import warnings
from datetime import datetime, timedelta, timezone
from pathlib import Path

warnings.filterwarnings("ignore")
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

# Same reason notebooks/_setup.py does this: we shell out to the `feast` CLI,
# which lives in the venv's bin dir. Running the script as `.venv/bin/python
# scripts/...` without activating the venv leaves that dir off PATH.
_BIN = Path(sys.executable).parent
if str(_BIN) not in os.environ.get("PATH", "").split(os.pathsep):
    os.environ["PATH"] = f"{_BIN}{os.pathsep}{os.environ.get('PATH', '')}"

QDRANT_URL = os.getenv("QDRANT_URL", "http://localhost:6333")
REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
PG_HOST = os.getenv("POSTGRES_HOST", "localhost")
PG_PORT = int(os.getenv("POSTGRES_PORT", "5432"))
PG_URL = f"postgresql://feast:feast@{PG_HOST}:{PG_PORT}/feast_offline"
# SQLAlchemy still resolves a bare `postgresql://` to psycopg2, which is not
# installed (feast's Postgres store uses psycopg 3). Name the driver.
PG_SA_URL = f"postgresql+psycopg://feast:feast@{PG_HOST}:{PG_PORT}/feast_offline"

DOCKER_REPO = ROOT / "app" / "feast_repo_docker"
LITE_REPO = ROOT / "app" / "feast_repo"
TOP_K = 10


def hr(title: str) -> None:
    print(f"\n{'─' * 72}\n{title}\n{'─' * 72}", flush=True)


# ── 1. services ─────────────────────────────────────────────────────────
def check_services() -> None:
    hr("1. Ba service của stack production")
    from qdrant_client import QdrantClient
    qc = QdrantClient(url=QDRANT_URL)
    cols = [c.name for c in qc.get_collections().collections]
    print(f"  Qdrant   {QDRANT_URL:32} OK   collections={cols}")

    import redis
    r = redis.Redis(host=REDIS_HOST, port=REDIS_PORT)
    assert r.ping()
    info = r.info("server")
    print(f"  Redis    {REDIS_HOST}:{REDIS_PORT:<26} OK   v{info['redis_version']}")

    import psycopg
    with psycopg.connect(PG_URL) as conn, conn.cursor() as cur:
        cur.execute("SELECT version()")
        ver = cur.fetchone()[0].split(",")[0]
    print(f"  Postgres {PG_HOST}:{PG_PORT:<26} OK   {ver}")


# ── 2. Feast on Redis + Postgres ────────────────────────────────────────
FEATURE_STORE_YAML = """\
# GENERATED by scripts/docker_path_report.py — do not commit.
project: lab19docker
provider: local
registry: registry.db
online_store:
  type: redis
  connection_string: {redis_host}:{redis_port}
offline_store:
  type: postgres
  host: {pg_host}
  port: {pg_port}
  database: feast_offline
  user: feast
  password: feast
  db_schema: public
  # Feast defaults to sslmode=require; the lab's postgres:16-alpine image is
  # built without SSL, so materialize dies with "server does not support SSL,
  # but SSL was required". Disabling it is fine for a loopback container --
  # a real deployment keeps TLS on and terminates it at the database.
  sslmode: disable
entity_key_serialization_version: 3
"""

DEFINITIONS_PY = '''\
"""GENERATED — same three feature views as app/feast_repo, Postgres-sourced."""
from datetime import timedelta

from feast import Entity, FeatureView, Field, ValueType
from feast.infra.offline_stores.contrib.postgres_offline_store.postgres_source import (
    PostgreSQLSource,
)
from feast.types import Float32, Int64, String

user = Entity(name="user", join_keys=["user_id"], value_type=ValueType.STRING)
item = Entity(name="item", join_keys=["doc_id"], value_type=ValueType.STRING)


def _src(name: str) -> PostgreSQLSource:
    return PostgreSQLSource(name=f"{name}_source", query=f"SELECT * FROM {name}",
                            timestamp_field="event_timestamp")


user_profile_features = FeatureView(
    name="user_profile_features", entities=[user], ttl=timedelta(days=30),
    schema=[Field(name="reading_speed_wpm", dtype=Int64),
            Field(name="preferred_language", dtype=String),
            Field(name="topic_affinity", dtype=String)],
    source=_src("user_profile"), online=True,
)

item_popularity_features = FeatureView(
    name="item_popularity_features", entities=[item], ttl=timedelta(hours=24),
    schema=[Field(name="click_count_24h", dtype=Int64),
            Field(name="ctr_7d", dtype=Float32),
            Field(name="avg_dwell_seconds", dtype=Float32)],
    source=_src("item_popularity"), online=True,
)

query_velocity_features = FeatureView(
    name="query_velocity_features", entities=[user], ttl=timedelta(hours=1),
    schema=[Field(name="queries_last_hour", dtype=Int64),
            Field(name="distinct_topics_24h", dtype=Int64)],
    source=_src("query_velocity"), online=True,
)
'''


def load_parquet_into_postgres() -> None:
    """The offline store is a warehouse in production; here it is Postgres.

    NB4 wrote three Parquet files. Feast's Postgres offline store reads SQL, so
    those same rows have to land in tables first — this is the ETL step that a
    real deployment does with dbt/Airflow rather than pandas.
    """
    import pandas as pd
    from sqlalchemy import create_engine

    src_dir = LITE_REPO / "data"
    files = sorted(src_dir.glob("*.parquet"))
    if not files:
        raise SystemExit(f"No parquet in {src_dir} — run NB4 first (it generates them).")
    engine = create_engine(PG_SA_URL)
    for f in files:
        df = pd.read_parquet(f)
        df.to_sql(f.stem, engine, if_exists="replace", index=False)
        print(f"  {f.stem:22} {len(df):>5} rows -> postgres")


def feast_docker() -> dict:
    hr("2. Feast trên Redis (online) + Postgres (offline)")
    DOCKER_REPO.mkdir(parents=True, exist_ok=True)
    (DOCKER_REPO / "feature_store.yaml").write_text(FEATURE_STORE_YAML.format(
        redis_host=REDIS_HOST, redis_port=REDIS_PORT,
        pg_host=PG_HOST, pg_port=PG_PORT), encoding="utf-8")
    (DOCKER_REPO / "definitions.py").write_text(DEFINITIONS_PY, encoding="utf-8")

    load_parquet_into_postgres()

    for cmd in (["feast", "apply"],
                ["feast", "materialize-incremental",
                 datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")]):
        res = subprocess.run(cmd, cwd=str(DOCKER_REPO), capture_output=True,
                             text=True, check=False)
        tag = " ".join(cmd[:2])
        print(f"\n  $ {' '.join(cmd)}  -> rc={res.returncode}")
        for line in (res.stdout or "").strip().splitlines()[-6:]:
            print(f"      {line}")
        if res.returncode != 0:
            print((res.stderr or "")[-800:])
            raise SystemExit(f"{tag} failed")

    from feast import FeatureStore
    fs = FeatureStore(repo_path=str(DOCKER_REPO))
    feats = ["user_profile_features:reading_speed_wpm",
             "user_profile_features:topic_affinity",
             "query_velocity_features:queries_last_hour"]

    got = fs.get_online_features(features=feats,
                                 entity_rows=[{"user_id": "u_001"}]).to_dict()
    print("\n  get_online_features(u_001) =",
          {k: v[0] for k, v in got.items()})

    for i in range(10):                                   # warm the connection
        fs.get_online_features(features=feats,
                               entity_rows=[{"user_id": f"u_{i:03d}"}]).to_dict()
    lat = []
    for i in range(100):
        t = time.perf_counter()
        fs.get_online_features(features=feats,
                               entity_rows=[{"user_id": f"u_{i:03d}"}]).to_dict()
        lat.append((time.perf_counter() - t) * 1000)
    lat.sort()
    out = {"p50": lat[50], "p95": lat[95], "p99": lat[99]}
    print(f"\n  Redis online lookup, 100 call:  "
          f"P50={out['p50']:.2f}ms  P95={out['p95']:.2f}ms  P99={out['p99']:.2f}ms")
    return out


# ── 3. Qdrant server mode ───────────────────────────────────────────────
def qdrant_server() -> dict:
    hr("3. Tìm kiếm trên Qdrant server (QDRANT_MODE=server)")
    os.environ["QDRANT_MODE"] = "server"
    os.environ["QDRANT_URL"] = QDRANT_URL
    from app.search import Searcher

    golden = [json.loads(l) for l in
              (ROOT / "data" / "golden_set.jsonl").open(encoding="utf-8")]
    t0 = time.perf_counter()
    searcher = Searcher.from_corpus(ROOT / "data" / "corpus_vn.jsonl")
    print(f"  indexed {searcher.size} docs vào Qdrant server in {time.perf_counter()-t0:.1f}s")

    def p_at_k(ids, rel):
        return sum(1 for d in ids[:TOP_K] if d in rel) / max(1, len(ids[:TOP_K]))

    quality, latency = {}, {}
    for mode in ("keyword", "semantic", "hybrid"):
        searcher.search(golden[0]["query"], mode=mode, top_k=TOP_K)   # warm
        ps, ls = [], []
        for _ in range(3):
            for q in golden:
                t = time.perf_counter()
                hits = [h.doc_id for h in searcher.search(q["query"], mode=mode, top_k=TOP_K)]
                ls.append((time.perf_counter() - t) * 1000)
                ps.append(p_at_k(hits, set(q["relevant_doc_ids"])))
        ls.sort()
        quality[mode] = stats.mean(ps)
        latency[mode] = {"p50": ls[len(ls) // 2], "p99": ls[int(len(ls) * 0.99)]}

    print(f"\n  {'mode':10}{'P@10':>9}{'P50':>10}{'P99':>10}")
    for mode in ("keyword", "semantic", "hybrid"):
        print(f"  {mode:10}{quality[mode]:>8.1%}{latency[mode]['p50']:>9.1f}ms"
              f"{latency[mode]['p99']:>9.1f}ms")
    return {"quality": quality, "latency": latency}


def main() -> int:
    print("Day 19 — báo cáo đường Docker (Qdrant server + Redis + Postgres)")
    check_services()
    redis_lat = feast_docker()
    vec = qdrant_server()

    hr("4. Lite so với Docker — cùng phép đo, khác hạ tầng")
    print("  Feast online lookup P99:")
    print(f"    SQLite (lite, xem NB4) : 1.35 ms   — file cục bộ, một process đọc được")
    print(f"    Redis  (docker)        : {redis_lat['p99']:.2f} ms   — qua TCP, mọi replica dùng chung")
    print("\n  Vector search P99 (in-process client -> Qdrant server, không qua HTTP API):")
    for mode in ("keyword", "semantic", "hybrid"):
        print(f"    {mode:10} {vec['latency'][mode]['p99']:>7.1f} ms   P@10 {vec['quality'][mode]:.1%}")
    print("\n  Chất lượng không đổi giữa hai path — đúng như mong đợi: đổi nơi cất\n"
          "  vector không đổi vector. Cái đổi là độ bền, khả năng chia sẻ và\n"
          "  một chặng mạng thêm vào mỗi lần đọc.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
